name: Test Plugin

on:
  pull_request:
    branches:
      - "main"
      - "patch*"
      - "dev"

jobs:
  structure-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Specify Python version

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -  # Install Poetry
          echo "$HOME/.local/bin" >> $GITHUB_PATH  # Add Poetry to PATH

      - name: Install dependencies
        run: |
          poetry install  # Install dependencies using Poetry

      - name: Run base tests
        run: |
          poetry run pytest -v -m pre_set

      - name: Run payload tests
        run: |
          poetry run pytest -v -m payload_set
